### ISSUE TITLE
Not handling a * character in a key

### ISSUE THREAD

**Issue by jmseaton** [jzbruno/terraconf#1]
I have a datadog_monitor resource in tfstate. One of the key pairs is `"silenced.*": "0",`

When I run terraconf, it returns nothing.  When I delete `"silenced.*": "0",` from tfstate, it runs fine and give the HCL output.

This is the full state file:
`{
    "version": 3,
    "terraform_version": "0.11.5",
    "serial": 1,
    "lineage": "2ab30d68-5233-b2a0-741c-d44041844f8a",
    "modules": [
        {
            "path": [
                "root"
            ],
            "outputs": {},
            "resources": {
                "datadog_monitor.3259218": {
                    "type": "datadog_monitor",
                    "depends_on": [],
                    "primary": {
                        "id": "3259218",
                        "attributes": {
                            "escalation_message": "",
                            "evaluation_delay": "0",
                            "id": "3259218",
                            "include_tags": "false",
                            "locked": "false",
                            "message": "TEST",
                            "name": "Anomoly Detected - Test",
                            "new_host_delay": "300",
                            "no_data_timeframe": "0",
                            "notify_audit": "false",
                            "notify_no_data": "false",
                            "query": "avg(last_30m):anomalies(avg:aws.elb.request_count{environment:prod} by {stack_role}.as_count(), 'agile', 2, direction='both', seasonality='weekly') \u003e 1",
                            "renotify_interval": "0",
                            "require_full_window": "true",
                            "silenced.%": "1",
                            "silenced.*": "0",
                            "tags.#": "1",
                            "tags.0": "*",
                            "thresholds.%": "1",
                            "thresholds.critical": "1.0",
                            "timeout_h": "0",
                            "type": "query alert"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": "provider.datadog"
                }
            },
            "depends_on": []
        }
    ]
}
`

**Comment by jmseaton** [comment]
dtd-tf]$ terraconf terraform.tfstate
dtd-tf]$ echo $?
1
dtd-tf]$

**Comment by jzbruno** [comment]
@jmseaton Thanks for reporting this. I will take a look tomorrow.

**Comment by jzbruno** [comment]
@jmseaton Looks like this was due to HCL not recognizing * as a valid key name in a map. This should be fixed now. I also fixed the error not being printed. 

Thanks for reporting the issue.

**Comment by jmseaton** [comment]
Awesome, it's working as expected, thank you!
